backend: af_xdp
output_dir: results/af_xdp_receiver0
interface_name: receiver0
queue_id: 22
duration_seconds: 5
max_burst: 64
packet_size_bytes: 512
status_interval_seconds: 10
feedback_interval_seconds: 1
feedback_enabled: true
feedback_host: 172.20.11.11
feedback_bind_host: 172.20.11.100
feedback_port: 9999
xdp_bind_mode: auto
xdp_rx_ring_size: 1024
xdp_tx_ring_size: 256
xdp_fill_ring_size: 2048
xdp_completion_ring_size: 2048
xdp_frame_size: 2048
xdp_frame_count: 4096
xdp_poll_timeout_ms: 0
reassembly_timeout_ms: 1000
run_until_stopped: true
cpu_cores: [16]
