backend: dpdk

[capture]
enabled = true
output_dir = results/dpdk_single_face
index_filename = capture_index.csv
data_filename = capture_packets.bin

[network]
interface_name = receiver0
queue_id = 0
receiver_ipv4 = 172.20.11.100
allowed_source_ipv4 = 172.20.11.222
allowed_dest_port = 9999

[dpdk]
pci_addr = 0001:05:00.0
port_id = 0
socket_mem_mb = 1024
mempool_size = 4096
mbuf_cache_size = 256
rx_desc = 256
tx_desc = 256

[runtime]
duration_seconds = 5
max_burst = 64
cpu_cores = [16,17]

[protocol]
udp_packet_size = 2048
channels_per_prt = 3
packets_per_channel = 9

[log]
level = info
output = stdout

[feedback]
enabled = false
interval_seconds = 1
